### ISSUE TITLE
Connect-DbaInstance does not work in Core when installed on a server with 2022

### ISSUE THREAD

**Issue by potatoqualitee** [dataplat/dbatools#8375]
### Verified issue does not already exist?

Yes

### What error did you receive?

```
PS C:\Users\cl\Documents\PowerShell\Modules\dbatools\1.1.98> Connect-DbaInstance -SqlInstance localhost
New-Object: C:\Users\cl\Documents\PowerShell\Modules\dbatools\1.1.98\functions\Connect-DbaInstance.ps1:881
Line |
 881 |  …   $server = New-Object -TypeName Microsoft.SqlServer.Management.Smo.S …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling ".ctor" with "1" argument(s): "Could not load type 'Microsoft.SqlServer.Server.SqlContext' from assembly 'System.Data, Version=4.0.0.0,
     | Culture=neutral, PublicKeyToken=b77a5c561934e089'."

InvalidOperation: C:\Users\cl\Documents\PowerShell\Modules\dbatools\1.1.98\functions\Connect-DbaInstance.ps1:902
Line |
 902 |  …             $server.ConnectionContext.StatementTimeout = $StatementTi …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The property 'StatementTimeout' cannot be found on this object. Verify that the property exists and can be set.

InvalidOperation: C:\Users\cl\Documents\PowerShell\Modules\dbatools\1.1.98\internal\functions\flowcontrol\Stop-Function.ps1:253
Line |
 253 |          throw $records[0]
     |          ~~~~~~~~~~~~~~~~~
     | Error connecting to [localhost]: You cannot call a method on a null-valued expression.
```

### Steps to Reproduce

1. Install SQL Server 2022 CTP
2. Install PowerShell Core
3. Install dbatools

Connect-DbaInstance localhost

### Are you running the latest release?

Yes

### Other details or mentions

Works in 5.1, works on a machine w/o 2022 installed, works after 2022 is uninstalled

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

newest

### SQL Server Edition and Build number

2022

### .NET Framework Version

All core:

PSChildName Version
----------- -------
Client      4.8.04161
Full        4.8.04161
Client      4.0.0.0

**Comment by potatoqualitee** [comment]
This seems to be an issue with 2022 and not us

```
PS> Add-Type -Path C:\Users\cl\Documents\PowerShell\Modules\dbatools\1.1.98\bin\smo\Microsoft.SqlServer.Smo.dll
Add-Type: Assembly with same name is already loaded
```

i dont understand enough to say

**Comment by potatoqualitee** [comment]
this was fixed by microsoft

**Comment by spaghettidba** [comment]
I am still getting the same after installing SQL Server 2022 on my workstation. How was still fixed by Microsoft? Do I need to patch SQL Server (tried this already, no joy)? SMO? Reinstall DbaTools?
