### ISSUE TITLE
`Test-DbaSpn` - `$ScriptBlock` Does Not Support PowerShell 2.0 Syntax

### ISSUE THREAD

**Issue by mattcargile** [dataplat/dbatools#8443]
### Verified issue does not already exist?

Yes

### What error did you receive?
```powershell
writeErrorStream      : True
PSMessageDetails      : 
Exception             : System.Exception: Cannot bind parameter 'FilterScript'. Cannot convert the "DisplayName" value of type "System.String" to type "System.Management.Automation.ScriptBlock". ---> 
                        System.Management.Automation.RemoteException: Cannot bind parameter 'FilterScript'. Cannot convert the "DisplayName" value of type "System.String" to type 
                        "System.Management.Automation.ScriptBlock".
                           --- End of inner exception stack trace ---
TargetObject          : 
CategoryInfo          : InvalidArgument: (:) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Test-DbaSpn,Stop-Function
ErrorDetails          : Cannot bind parameter 'FilterScript'. Cannot convert the "DisplayName" value of type "System.String" to type "System.Management.Automation.ScriptBlock".
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.113\allcommands.ps1: line 147954
                        at Test-DbaSpn<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.113\allcommands.ps1: line 133039
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}
```
### Steps to Reproduce

```powershell
# Find machine with powershell.exe 2.0
Test-DbaSpn -ComputerName RemoteServer
```

### Are you running the latest release?

Yes

### Other details or mentions

`$ScriptBlock` uses `Where-Object` with a modern syntax. Powershell 2.0 only appears to support the `-FilterScript` syntax. On servers with `powershell.exe` v2.0. The command will fail. The fix, I believe, is to wrap the _applicable_ below lines in the older `{ }` syntax. It would be helpful to use the `-FilterScript` syntax below for folks on older servers. I do understand the goal to support new versions. I have another Issue for an internal command that could help this. It would be helpful to fix this code path for me because this code path is used if I use Powershell core I believe because the Wmi Management library can't be loaded.

https://github.com/dataplat/dbatools/blob/ced439756a413c366af63299fa25a34d930e8fa6/functions/Test-DbaSpn.ps1#L146-L161

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe), Windows PowerShell (powershell.exe)

#### Local

```powershell
Name                           Value                                                                                                                                                                            
----                           -----                                                                                                                                                                            
PSVersion                      5.1.19041.1682                                                                                                                                                                   
PSEdition                      Desktop                                                                                                                                                                          
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                          
BuildVersion                   10.0.19041.1682                                                                                                                                                                  
CLRVersion                     4.0.30319.42000                                                                                                                                                                  
WSManStackVersion              3.0                                                                                                                                                                              
PSRemotingProtocolVersion      2.3                                                                                                                                                                              
SerializationVersion           1.1.0.1               
```                                                                                                                                                           
#### Remote
```powershell
Name                           Value                                                                                                                                      
----                           -----                                                                                                                                      
CLRVersion                     2.0.50727.8806                                                                                                                             
BuildVersion                   6.1.7601.17514                                                                                                                             
PSVersion                      2.0                                                                                                                                        
WSManStackVersion              2.0                                                                                                                                        
PSCompatibleVersions           {1.0, 2.0}                                                                                                                                 
SerializationVersion           1.1.0.1                                                                                                                                    
PSRemotingProtocolVersion      2.1                                                                                                                                        
```

### SQL Server Edition and Build number

```sql
Microsoft SQL Server 2008 (SP4-GDR) (KB4057114) - 10.0.6556.0 (X64) 
	Dec 28 2017 15:21:01 
	Copyright (c) 1988-2008 Microsoft Corporation
	Enterprise Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1) (VM)
```

#### Local
```powershell
.NET Framework 4.8.4515.0
```
#### Remote
```powershell
PSChildName                      Version       
-----------                      -------       
v2.0.50727                       2.0.50727.5420
v3.0                             3.0.30729.5420
Windows Communication Foundation 3.0.4506.5420 
Windows Presentation Foundation  3.0.6920.5011 
v3.5                             3.5.30729.5420
Client                           4.0.30319     
Full                             4.0.30319     
```

**Comment by potatoqualitee** [comment]
It's so hard to say yes because PS 2.0 presents a security risk. I also don't want to start a trend of modifying multiple commands to support 2.0. But I will make one exception and accept one PR with the change, as SPNs are important, more secure and worth the tradeoff. I believe your suggested changes are correct.

Also, good news, SQLWMI does indeed work on _Windows_ PowerShell Core! 

![image](https://user-images.githubusercontent.com/8278033/180147808-7e764a08-9ca8-4a8a-b859-42e93ec0287f.png)

**Comment by andreasjordan** [comment]
Hi @mattcargile - as the bug in Invoke-ManagedComputerComm is now fixed: Can you retry using Test-DbaSpn against an old server? Maybe it works because the WMI call in now started from your source server and not executed via WinRM.

**Comment by mattcargile** [comment]
I guess it depends on if we want to support `pwsh` _Core_ which I would strongly want. In this current build, `Test-DbaSpn` now works on `powershell` _Desktop_. It still fails on _Core_ because the `[scriptblock]` has to execute on the remote server ( e.g. `powershell` v2 ). On the other hand, calls to `Test-DbaSpn` on _Desktop_ work because the .NET library exists on _Desktop_.

In conclusion, I would really like to see the `Where-Object -FilterScript { $_.Var -eq 'Data' }` syntax used. Below is the code changes for the applicable [lines](https://github.com/dataplat/dbatools/blob/ced439756a413c366af63299fa25a34d930e8fa6/functions/Test-DbaSpn.ps1#L146-L161).

```powershell
                    $services = $wmi.Services | Where-Object { $_.DisplayName -EQ "SQL Server ($instanceName)" }
                    $spn.InstanceServiceAccount = $services.ServiceAccount
                    $spn.Cluster = ($services.advancedproperties | Where-Object { $_.Name -EQ 'Clustered' } ).Value

                    if ($spn.Cluster) {
                        $hostEntry = ($services.advancedproperties | Where-Object { $_.Name -EQ 'VSNAME' }).Value.ToLowerInvariant()
                        <# DO NOT use Write-Message as this is inside of a script block #>
                        Write-Verbose "Found cluster $hostEntry"
                        $hostEntry = ([System.Net.Dns]::GetHostEntry($hostEntry)).HostName
                        $spn.ComputerName = $hostEntry
                    }

                    $rawVersion = [version]($services.AdvancedProperties | Where-Object { $_.Name -EQ 'VERSION' }).Value

                    $version = Convert-SqlVersion $rawVersion
                    $skuName = ($services.AdvancedProperties | Where-Object { $_.Name -EQ 'SKUNAME' }).Value
```

**Comment by andreasjordan** [comment]
Ok, I will try to find some time for this change tomorrow.

**Comment by andreasjordan** [comment]
@mattcargile - I included your changes in a bugfix-PR. But can you please check if  `.Split()` is supported in PowerShell 2.0? If not, I can change that to `-split`.

**Comment by wsmelton** [comment]
There is no reason to support PS 2 even on remote servers. Windows Server 2008 and higher all can have Windows PowerShell v5 installed.

**Comment by mattcargile** [comment]
> @mattcargile - I included your changes in a bugfix-PR. But can you please check if `.Split()` is supported in PowerShell 2.0? If not, I can change that to `-split`.

For what it is worth, @andreasjordan , usage like `'hello.world'.split( '.' )` does work in _2.0_.

**Comment by andreasjordan** [comment]
Fixed with https://github.com/dataplat/dbatools/pull/8901.
